# Generated by Django 3.2.25 on 2025-12-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=20, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('total', models.PositiveIntegerField(default=1, verbose_name='总册数')),
                ('available', models.PositiveIntegerField(default=1, verbose_name='在馆册数')),
                ('status', models.CharField(choices=[('available', '可借'), ('borrowed', '已借完')], default='available', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'books',
            },
        ),
    ]
