# Generated by Django 5.2.7 on 2025-12-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='apply_status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=8, verbose_name='申请状态'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='return_request_status',
            field=models.CharField(choices=[('none', '无'), ('requested', '已申请'), ('confirmed', '已确认')], default='none', max_length=10, verbose_name='还书申请状态'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(blank=True, null=True, verbose_name='借出日期'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='应还日期'),
        ),
    ]
