"""
Django settings for library_ms project.
Generated by 'django-admin startproject' using Django 4.2.
"""

# 创建自定义数据库引擎类来绕过版本检查
from django.db.backends.mysql import base

# 保存原始的check_database_version_supported方法
original_check = base.Database.check_database_version_supported

# 重写该方法以禁用版本检查
def patched_check(self):
    # 跳过版本检查
    pass

# 替换方法
base.Database.check_database_version_supported = patched_check

from pathlib import Path
from decouple import config                      # 新增：读取 .env

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-*b9(#o0sj7=1-ou(=#8gf6wc4fqkb4cz3e+98(rwh%^0ti7v0*'
DEBUG = True
ALLOWED_HOSTS = ['*']                            # 允许本地&局域网调试

# ****************  应用列表  ****************
INSTALLED_APPS = [
    'admins',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 自建 APP
    'accounts',
    'books',
    'categories',
    'borrows',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'library_ms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],        # 预留模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'library_ms.wsgi.application'

# ****************  MySQL 配置  ****************
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PWD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
# ****************  国际化  ****************
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# ****************  静态文件  ****************
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 使用自定义用户模型
AUTH_USER_MODEL = 'accounts.User'
# 设置登录URL
LOGIN_URL = '/login/'